<h1>넘파이</h1>
<h2>넘파이 ndarray 개요</h2>

In [5]:
import numpy as np
array1= np.array([1, 2, 3])
print(type(array1))
print(array1.shape)
array2= np.array([[1, 2, 3],
                 [4, 5, 6]])
print(array2.shape)
print(array1.ndim) #ndarray의 차원을 나타냄
print(array2.ndim)


<class 'numpy.ndarray'>
(3,)
(2, 3)
1
2


<h2>ndarray의 데이터 타입</h2>
숫자 값, 문자열 값, 부울 값 모두 가능<br>
같은 데이터 타입끼리만 연산 가능<br>
한개의 ndarray객체에 다른 데이터 타입이 같이 있을 수 없음(리스트는 가능)

In [7]:
list=[1, 2, 'dog', 4]
array1= np.array(list)
print(array1) #ndarray는 다른 데이터 유형이 섞여있는 리스트를 ndarray로 변환하면, 데이터 크기가 더 큰 타입으로 형 일괄 변환


['1' '2' 'dog' '4']


In [8]:
#ndarray내 데이터 값 타입 변경
#메모리를 절약해야할 때 주로 이용
array_int= np.array([1, 2, 3])
array_float= array_int.astype('float64')
print(array_float, array_float.dtype)

[1. 2. 3.] float64


<h2>ndarray를 편하게 생성 - arange, zeros, ones</h2>

In [10]:
#arange()는 range와 유사하게 0부터 함수 인자 -1까지 ndarray반환
sequence= np.arange(5)
print(sequence, type(sequence))
sequence2= np.arange(1, 10, 2)
print(sequence2, type(sequence2))

[0 1 2 3 4] <class 'numpy.ndarray'>
[1 3 5 7 9] <class 'numpy.ndarray'>


In [16]:
#zeros는 튜플 형태의 shape값을 입력하면 모든 값이 0으로 채워지고 해당 shape을 가진 ndarray반환
zeros_array= np.zeros((2, 3)) #dtype을 입력하지 않으면 float64형 데이터로 채움
print(zeros_array, zeros_array.dtype) 

#ones는 모든 값을 1로 채운 ndarray반환
ones_array= np.ones((3, 4), dtype='int32')
print(ones_array, ones_array.dtype)

[[0. 0. 0.]
 [0. 0. 0.]] float64
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] int32


<h2>ndarray 차원과 크기 변경 </h2>

In [25]:
#지정된 사이즈로 변환이 불가하면 에러
array1= np.arange(10)
print(array1)
array2= array1.reshape(2, 5)
print(array2)

#reshape인자로 -1을 적용하는 경우, 행과 열중 고정된 것에 맞추어 변환
array3= array1.reshape(-1, 5)
print(array3)
array4= array1.reshape(-1, 2)
print(array4)

#주로 reshape(-1 ,1)형태를 많이 사용하는데 reshape(-1, 1)은 ndarray가 어떤 형태라도 2차원이고 
#여러개의 로우를 가지고 하나의 칼럼을 가지는 ndarray로 반환됨을 보장
array1= np.arange(8)
print(array1)
array2= array1.reshape(-1, 1)
print(array2)
array3= array1.reshape(2, 2, 2)
print(array3)
array4= array3.reshape(-1, 1)
print(array4)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0 1 2 3 4 5 6 7]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


<h2>넘파이의 ndarray의 데이터 셋 선택하기 - 인덱싱</h2>
1.특정한 데이터만 추출:원하는 위치의 인덱스값 지정<br>
2.슬라이싱: 연속된 인덱스상의 ndarray 추출, 시작인덱스:종료인덱스, 종료인덱스 -1의 인덱스의 값까지 추출
3.팬시 인덱싱:일정한 인덱싱 집합을 리스트 또는 ndarray형태로 지정<br>
4.불린 인덱싱: 특정조건에 해당하는지 여부인 true/false값 인덱싱 집합을 기반으로 true에 해당하는 인덱스 위치에 있는 데이터 반환

In [39]:
#단일값 추출
array1= np.arange(10)
print(array1[1])
print(array1[-1]) #맨 뒤의 값
print(array1[-2]) #맨 뒤에서 두번째 값

#다차원 ndarray에서 단일 값 추출
array1d= np.arange(8)
array2d= array1d.reshape(-1, 2)
print(array2d)
print(array2d[1,1])

1
9
8
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
3


In [40]:
#슬라이싱
array1= np.arange(1, 10)
print(array1[0:3])
#1. :기호앞에 시작 인덱스를 생략하면 0으로 간주
#2. :기호 뒤에 종료 인덱스를 생략하면 마지막 인덱스로 간주
#3. :기호 앞뒤를 모두 생략하면 맨처음/ 마지막 인덱스로 간주

array2d= array1.reshape(-1, 3)
print(array2d)
print(array2d[0:2, 0:2])
print(array2d[1]) #2차원 ndarray에서 열 인덱스를 생략하면 로우 축만 반환(1차원이 됨)

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[4 5 6]


In [43]:
#팬시 인덱싱
array1d= np.arange(1, 10)
array2d= array1d.reshape(-1, 3)

print(array2d[[0,1],1]) #로우 축에서 0,1인덱스, 칼럼 축에서 1인덱스
print(array2d[[1, 2], 0:2]) #로우 축에서 1,2 인덱스, 칼럼 축에서 0,1인덱스

[2 5]
[[4 5]
 [7 8]]


In [44]:
#불린 인덱싱
array1d= np.arange(1, 10)
array3d= array1d[array1d>5]
print(array3d)
#1. ndarray의 필터링 조건을 []안에 기재
#2. true값에 해당하는 인덱스 값 저장
#3. 저장된 인덱스 데이터 세트로 ndarray 조회


[6 7 8 9]


<h2>행렬의 정렬 - sort(), argsort()</h2>

In [57]:
#1. np.sort 원행렬은 그대로 두고 원행렬의 정렬된 행렬 반환
#2. ndarray.sort 원행렬을 정렬함, 반환값은 None
org_array= np.array([3, 1, 9 ,5])
print(org_array) #np.sort
sort_array= np.sort(org_array)
print(sort_array)
org_array.sort() #ndarray.sort
print(org_array)

#내림차순 정렬
org_array= np.array([3, 1, 9, 5])
sort_array_desc= np.sort(org_array)[::-1]
print(sort_array_desc)

#행렬이 2차원 이상일 경우 axis 축 값 설정을 통해 로우, 칼럼 방향으로 정렬 수행
org_array2d= np.array([[6, 5],
                      [4, 3]])
sort_array2d_axis_0= np.sort(org_array2d, axis=0)
print(sort_array2d_axis_0) #행을 기준으로 작은 행이 위로 올라감
sort_array2d_axis_1= np.sort(org_array2d, axis=1)
print(sort_array2d_axis_1) #열을 기준으로 작은 열이 앞으로 나옴

#argsort()는 원행렬이 정렬 되었을 때의 해당 인덱스 반환
org_array= np.array([4, 5, 1, 2])
sort_ind= np.argsort(org_array)
print(sort_ind)

#argsort() 활용
name_array= np.array(['John', 'Mike', 'Judy', 'Sarah', 'Karon'])
score_array= np.array([43, 76, 22, 95, 55])

sort_score_ind= np.argsort(score_array)
print(sort_score_ind)
print(name_array[sort_score_ind]) # 성적이 낮은순으로 이름이 나옴

[3 1 9 5]
[1 3 5 9]
[1 3 5 9]
[9 5 3 1]
[[4 3]
 [6 5]]
[[5 6]
 [3 4]]
[2 3 0 1]
[2 0 4 1 3]
['Judy' 'John' 'Karon' 'Mike' 'Sarah']


<h2>선형대수 연산- 행렬 내적과 전치행렬 구하기</h2>

In [60]:
#행렬 내적
A= np.array([[2, 1],
            [3, 5]])
B= np.array([[2, 2],
             [4, 6]])
dot_product= np.dot(A, B)
print(dot_product)

#전치 행렬
A_transpose= A.T
print(A_transpose)

A_transpose= np.transpose(A)
print(A_transpose)

[[ 8 10]
 [26 36]]
[[2 3]
 [1 5]]
[[2 3]
 [1 5]]
