<h1>데이터 핸들링 - 판다스</h1>
핵심객체는 DataFrame
Index와 Series객체에 대한 이해도 중요

<h2>판다스 시작 - 파일을 DataFrame으로 로딩</h2>

In [1]:
import pandas as pd
#DataFrame으로 로딩할 수 있는 API
#read_csv, read_table, read_fwf
#read_csv는 칼럼을 ',' 로 구분한 파일포맷을 DataFrame객체로 반환
#read_table은 칼럼을 '\t' 로 구분한 파일 포맷, read_csv(sep='\t')으로 대체가능.
#read_fwf는 고정 길이 기반의 칼럼 포맷을 로딩하기 위한 API
titanic_df= pd.read_csv('titanic.csv')
titanic_df.head(3) #데이터프레임 맨앞에 있는 3개의 로우 반환
print(type(titanic_df))

#read_csv는 호출시 별다른 파라미터 지정이 없으면 맨 처음 로우를 칼럼명으로 지정
#데이터 프레임의 행과 열을 튜플 형태로 반환
print(titanic_df.shape) 

#데이터의 분포, 칼럼의 타입, 메타 데이터 등 조회
print(titanic_df.info())

#칼럼별 숫자형 데이터 값의 n_percentile 분포, 평균값, 최댓값, 최솟값 나타냄
#count는 not_null인 건수, mean은 전체 데이터 평균
print(titanic_df.describe()) 

#value_counts()는 해당 칼럼값의 유형과 건수 확인가능, value_count()는 series객체에서만 사용 가능
value_counts= titanic_df['Pclass'].value_counts()
print(value_counts)

#DataFrame의 []연산자 내부에 칼럼명을 입력하면 Series객체 반환
titanic_pclass= titanic_df['Pclass']
print(type(titanic_pclass))



<class 'pandas.core.frame.DataFrame'>
(891, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None
       PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699

<h2>DataFrame과 리스트, 딕셔너리, 넘파이 ndarray 상호 변환</h2>

In [3]:
#넘파이 ndarray, 리스트, 딕셔너리를 DataFrame으로 변환
#판다스 DataFrame 객체의 생성인자 data는 리스트나 딕셔너리 또는 넘파이 ndarray를 입력 받고, 
#생성인자 columns는 칼럼명 리스트를 입력 받아서 DataFrame생성
import numpy as np
import pandas as pd
col_name1=['col1']
list1= [1, 2, 3]
array1= np.array(list1)
print(array1.shape,'\n')
#리스트를 이용해 DF생성
df_list1= pd.DataFrame(list1, columns= col_name1)
print(df_list1,'\n')

#넘파이 ndarray를 이용해 DF생성
df_array1= pd.DataFrame(array1, columns=col_name1)
print(df_array1,'\n')

#3개의 칼럼명
col_name2= ['col1', 'col2', 'col3']

#2행 * 3열 형태의 리스트와 ndarray 생성한뒤 이를 DF로 변환
list2= [[1, 2, 3],
       [4, 5, 6]]
array2= np.array(list2)
print(array2.shape,'\n')
df_list2= pd.DataFrame(list2, columns=col_name2)
print(df_list2,'\n')
df_array2= pd.DataFrame(array2, columns=col_name2)
print(df_array2,'\n')

#딕셔너리를 DataFrame으로 변환, 키는 칼럼명으로 값은 칼럼 데이터로 변환
dict= {'col1':[1, 11], 'col2':[2, 22], 'col3':[3, 33]}
df_dict= pd.DataFrame(dict)
print(df_dict)

(3,) 

   col1
0     1
1     2
2     3 

   col1
0     1
1     2
2     3 

(2, 3) 

   col1  col2  col3
0     1     2     3
1     4     5     6 

   col1  col2  col3
0     1     2     3
1     4     5     6 

   col1  col2  col3
0     1     2     3
1    11    22    33


In [3]:
#DataFrame을 넘파이 ndarray, 리스트, 딕셔너리로 변환
#DataFrame을 ndarray로 변환, 데이터 프레임 객체에 values함수 적용
array3= df_dict.values
print(type(array3), array3.shape)
print(array3)

#DataFrame을 리스트로 변환, ndarray에 tolist()호출
list3= df_dict.values.tolist()
print(type(list3))
print(list3)

#DataFrame을 딕셔너리로 변환, 딕셔너리의 값이 리스트형으로 반환
dict3= df_dict.to_dict('list')
print(type(dict3))
print(dict3)

<class 'numpy.ndarray'> (2, 3)
[[ 1  2  3]
 [11 22 33]]
<class 'list'>
[[1, 2, 3], [11, 22, 33]]
<class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}


<h2>DataFrame의 칼럼 데이터 세트 생성과 수정</h2>

In [4]:
#DataFrame의 칼럼 데이터 셋 생성
titanic_df['Age_0']=0
titanic_df.head(3)

titanic_df['Age_by_10'] =titanic_df['Age']*10
titanic_df['Family_No']= titanic_df['SibSp'] + titanic_df['Parch']+1
titanic_df.head(3)

#기존 칼럼 값 수정
titanic_df['Age_by_10']= titanic_df['Age_by_10']+100
titanic_df.head(3)



PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0      0         A/5 21171   7.2500   NaN        S      0      320.0   
1      0          PC 17599  71.2833   C85        C      0      480.0   
2      0  STON/O2. 3101282   7.9250   NaN        S      0      360.0   

   Family_No  
0          2  
1          2  
2          1

<h2>DataFrame 데이터 삭제</h2>

In [5]:
#DataFrame.drop(labels, axis, index, columns, level, inplace, errors)
#axis=0을 입력하면 labels에 오는 값을 인덱스로 간주, axis=1을 입력하면 labels에 칼럼 명을 입력하면 됨
#열 삭제
titanic_drop_df= titanic_df.drop('Age_0', axis=1)
titanic_drop_df.head(3)

#inplace=False가 default이고, True로 설정하면 원본 DataFrame의 칼럼을 삭제하고 None반환

#행 삭제
#titanic_df.drop([0, 1, 2], axis=0, inplace=True)


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_by_10  Family_No  
0      0         A/5 21171   7.2500   NaN        S      320.0          2  
1      0          PC 17599  71.2833   C85        C      480.0          2  
2      0  STON/O2. 3101282   7.9250   NaN        S      360.0          1

<h2>Index 객체</h2>
판다스의 index객체는 DataFrame, Series의 레코드를 고유하게 식별하는 객체<br>
DataFrame.index, Series.index를 통해 추출할 수 있음

In [6]:
titanic_df= pd.read_csv('titanic.csv')

#index 객체 추출
indexes= titanic_df.index
print(indexes)

#index 객체를 실제 값 array로 변환
#print(indexes.values)

#index 객체는 식별성 데이터를 가진 1차원 array이므로 ndarray와 유사하게 단일 값 반환 및 슬라이싱 가능
print(type(indexes.values))
print(indexes.values.shape)
print(indexes[:5].values)
print(indexes.values[:5])
print(indexes[6])

#DataFrame이나 Series의 index 객체는 함부로 변경 불가
#Series 객체는 index 객체를 포함하지만 index객체는 연산에서 제외되고, 오로지 식별용으로 사용

#DataFrame이나 Series에 reset_index()메서드를 수행하면 새로운 인덱스를 할당하고, 기존인덱스는 index라는 새로운 칼러명으로 추가
titanic_reset_df= titanic_df.reset_index(inplace=False)
titanic_reset_df.head(3)
#reset_index는 인덱스가 연속된 int 숫자형 데이터가 아닐 경우에 다시 이를 연속 int 숫자형 데이터로 만들때 주로 사용

value_counts= titanic_df['Pclass'].value_counts()
print(value_counts)
print(type(value_counts))
new_value_counts= value_counts.reset_index(inplace=False)
print(new_value_counts)
#reset_index()의 파라미터중 drop=True로 설정하면 기존 인덱스는 칼럼으로 추가되지 않고 삭제됨

#데이터 셀렉션 및 필터링
#numpy의 []연산자와 차이가 있음

#DataFrame의 []연산자는 칼럼만 지정할 수 있는 '칼럼 지정 연산자'임
#DataFrame의 []에는 칼럼명을 지정해야 함
print(titanic_df['Pclass'].head(3))
#판다스의 인덱스 형식으로 변환 가능한 표현식은 []안에 입력가능
titanic_df1= titanic_df[0:2]
#불린 인덱싱 표현도 가능
titanic_df2= titanic_df[titanic_df['Pclass']==3].head(3)
print(titanic_df2)
#DataFrame의 뒤의 []연산자의 입력 인자가 여러가지 형태이므로 혼란을 방지 하기 위한 가이드
#1. DataFrame바로 뒤의 []연산자는 numpy의 []나 series의 []와 다름
#2. DataFrma바로 뒤의 []내 입력값은 칼럼명을 지정해 사용하거나 불린 인덱스 용도로만 사용
#3. DataFrame[0:2] 같은 슬라이싱 연산은 사용하지 않는게 좋음



RangeIndex(start=0, stop=891, step=1)
<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6
3    491
1    216
2    184
Name: Pclass, dtype: int64
<class 'pandas.core.series.Series'>
   index  Pclass
0      3     491
1      1     216
2      2     184
0    3
1    1
2    3
Name: Pclass, dtype: int64
   PassengerId  Survived  Pclass                      Name     Sex   Age  \
0            1         0       3   Braund, Mr. Owen Harris    male  22.0   
2            3         1       3    Heikkinen, Miss. Laina  female  26.0   
4            5         0       3  Allen, Mr. William Henry    male  35.0   

   SibSp  Parch            Ticket   Fare Cabin Embarked  
0      1      0         A/5 21171  7.250   NaN        S  
2      0      0  STON/O2. 3101282  7.925   NaN        S  
4      0      0            373450  8.050   NaN        S  


In [7]:
#명칭기반 인덱싱과 위치 기반 인덱싱의 구분
#명칭기반 인덱싱은 칼럼의 명칭을 기반으로 위치를 지정하는 방식
#위치 기반 인덱싱은 0을 출발점으로 하는 가로축, 세로축 좌표 기반의 행과 열 위치를 기반으로 데이터 지정
#DataFrame iloc[]연산자, 위치기반 인덱싱
#DataFrame loc[]연산자, 명칭기반 인덱싱

#불린 인덱싱
#[], ix[], loc[]에서 공통으로 지원, iloc[]에서는 지원 안함
titanic_df= pd.read_csv('titanic.csv')
titanic_boolean= titanic_df[titanic_df['Age']>60]
print(titanic_boolean)
print(type(titanic_boolean))

###칼럼이 두개 이상(데이터 프레임을 빼올때)이면 대괄호를 두개 써야함###
print(titanic_df[titanic_df['Age']>60][['Name','Age']].head(3))

#loc[]을 이용해도 동일하게 적용, 단 ['Name',' Age']는 칼럼위치에 놓여야 함
titanic_df.loc[titanic_df['Age']>60, ['Name','Age']].head(3)

#복합 조건
titanic_df[(titanic_df['Age']>60)&(titanic_df['Pclass']==1)&(titanic_df['Sex']=='female')]

cond1= titanic_df['Age']>60
cond2= titanic_df['Pclass']==1
cond3= titanic_df['Sex']=='female'
titanic_df[cond1&cond2&cond3]



     PassengerId  Survived  Pclass                                       Name  \
33            34         0       2                      Wheadon, Mr. Edward H   
54            55         0       1             Ostby, Mr. Engelhart Cornelius   
96            97         0       1                  Goldschmidt, Mr. George B   
116          117         0       3                       Connors, Mr. Patrick   
170          171         0       1                  Van der hoef, Mr. Wyckoff   
252          253         0       1                  Stead, Mr. William Thomas   
275          276         1       1          Andrews, Miss. Kornelia Theodosia   
280          281         0       3                           Duane, Mr. Frank   
326          327         0       3                  Nysveen, Mr. Johan Hansen   
438          439         0       1                          Fortune, Mr. Mark   
456          457         0       1                  Millet, Mr. Francis Davis   
483          484         1  

PassengerId  Survived  Pclass                                       Name  \
275          276         1       1          Andrews, Miss. Kornelia Theodosia   
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   

        Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked  
275  female  63.0      1      0   13502  77.9583    D7        S  
829  female  62.0      0      0  113572  80.0000   B28      NaN

<h2>정렬, Aggregation 함수, GroupBy 적용</h2>
DataFrame, Series의 정렬 - sort_values()

In [8]:
titanic_df_sorted= titanic_df.sort_values(by=['Name'])
titanic_df_sorted.head(3)
print(type(titanic_df_sorted))
titanic_df_sorted2= titanic_df.sort_values(by=['Pclass', 'Name'])
print(titanic_df_sorted2.head(3))

#Aggregation 함수 적용
titanic_df.count()
#특정 칼럼에 aggregation 함수 적용
titanic_df[['Age', 'Fare']].mean()

#groupby() 적용
titanic_groupby= titanic_df.groupby(by='Pclass')
print(type(titanic_groupby))

#DataFrame에 groupby()호출해 반횐된 결과에 aggregation함수를 호출하면
#groupby() 대상 칼럼을 제외한 모든 칼럼에 aggregation함수를 적용
titanic_groupby= titanic_df.groupby('Pclass').count()
titanic_groupby

titanic_groupby= titanic_df.groupby('Pclass')[['PassengerId', 'Survived']].count()
titanic_groupby

titanic_df.groupby('Pclass')['Age'].agg([max, min])

#여러개의 칼럼이 서로다른 aggregation함수 호출
agg_format={'Age':'max', 'SibSp':'sum','Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

<class 'pandas.core.frame.DataFrame'>
     PassengerId  Survived  Pclass                            Name     Sex  \
730          731         1       1   Allen, Miss. Elisabeth Walton  female   
305          306         1       1  Allison, Master. Hudson Trevor    male   
297          298         0       1    Allison, Miss. Helen Loraine  female   

       Age  SibSp  Parch  Ticket      Fare    Cabin Embarked  
730  29.00      0      0   24160  211.3375       B5        S  
305   0.92      1      2  113781  151.5500  C22 C26        S  
297   2.00      1      2  113781  151.5500  C22 C26        S  
<class 'pandas.core.groupby.generic.DataFrameGroupBy'>


Age  SibSp       Fare
Pclass                        
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

In [9]:
#결손 데이터 처리하기
#결손데이터는 칼럼에 값이 없는 null인 경우를 의미하고 이를 넘파이의 NaN으로 표시

#isna()로 결손 데이터 여부 확인
titanic_df.isna().head(3)
titanic_df.isna().sum()

#fillna()로 결손 데이터 대체하기, 반환값을 칼럼에 넣거나 inplace=Ture로 해야함
titanic_df['Cabin']= titanic_df['Cabin'].fillna('C000')
titanic_df.head(3)

titanic_df['Age']= titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Embarked']= titanic_df['Embarked'].fillna('S')
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

<h2>apply lambda 식으로 데이터 가공</h2>

In [10]:
#apply함수에 lambda식을 결합해 DataFrame이나 Series의 레코드별로 데이터를 가공하는 기능
lambda_square= lambda x: x**2
print(lambda_square(3))

#입력 인자로 여러개 사용
a=[1, 2, 3]
squares= map(lambda x: x**2, a)
list(squares)

#DataFrame에서 lambda식, apply에 lambda식으로 적용
titanic_df['Name_len']= titanic_df['Name'].apply(lambda x:len(x))
titanic_df[['Name', 'Name_len']].head(3)

#lambda식 내에서 if, else지원
titanic_df['Age_cat']= titanic_df['Age'].apply(lambda x: 'Child' if x<15 else('Adult' if x<=60 else 'Elderly'))
titanic_df['Age_cat'].value_counts()
print(titanic_df.dtypes)

9
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
Name_len         int64
Age_cat         object
dtype: object
