<h2>숫자</h2>
<h3>정수</h3>
정수는 int로 나타내며 불변형<br>
파이썬 정수 크기는 적어도 32비트(4바이트)<br>
정수를 나타내는 데 필요한 바이트수 확인 (정수).bit_length()

In [1]:
(999).bit_length()

10

In [3]:
#어떤 문자열 정수로 변환하거나 다른 진법의 문자열을 10진법으로 변환
#int(문자열, 밑)
s= '11'
d= int(s)
print(d)

b= int(s, 2) #이진수
print(b)

11
3


<h3>부동소수점</h3>
파이썬에서 부동소수점은 float으로 나타내며 불변형<br>
단정도 방식에서 32비트 부동소수점을 나타낼때 1비트는 부호(0:양수, 1:음수)<br>
23비트는 유효숫자 자릿수(가수부), 8비트는 지수<br>
배정도 방식은 64비트, double로 나타내며 불변형<br>

![](IMG/number1.jpg)

![](IMG/number2.jpg)

2진수로는 0.3, 0.1등등의 수를 완벽하게 나타낼 수 

변환된 이진수를 정규화<br>
1110110.101(2)= 1.110110101(2) * 2 ** 6<br>
위의 숫자를 가수부에 넣고 부족한 자릿수는 0으로 채움<br>
지수는 6이므로 바이어스를 더함, 즉 지수 6에 127을 더함<br>
6+ 127= 133= 10000101(2) <br>
따라서 -118.624(10)를 32비트 단정도로 표현한 결과는
1 10000101 110110101임<br>
단정도 방식일때는 지수에 127(2 ** 7-1)을 더하고, 배정도 방식일때 1023(2 ** 10-1)을 더함

<h4>부동소수점끼리 비교하기</h4>
부동소수점은 이진수 분수로 표현되기 때문에 함부로 비교하거나 빼면 안됨<br>
2진수는 대개 10진법으로 정확하게 표현되지만, 2진법으로 표현하기 어려운 숫자도 있음 (ex 0.1)
그 대신 동등성 테스트는 사전에 정의된 정밀도 범위 내에서 수행되어야 함<br>
예를 들어 unittest 모듈의 assertAlmostEqual메서드를 <br>
def a(x, y, places=7):<br>
    return round(abs(x-y), places)==0<br>

<h4>정수와 부동소수점 메서드</h4>
파이썬에서 나누기 연산자 / 는 항상 부동소수점을 반환<br>
//연산자는 정수를 반환<br>
%연산자는 나머지 반환<br>

In [8]:
divmod(45, 6) #몫과 나머지 반환
round(113.866, -1) #round(x, n) n이 음수인 경우 정수 n번째 자리에서  반올림
#round(x, n) n이 양수인 경우 소수 n+1자릿수에서 반올림 
2.75.as_integer_ratio() #부동소수점 분수로 표현

(11, 4)

<h3>복소수</h3>
복소수는 z=3+4i와 같이 생긴 부동소수점 한쌍을 갖는 불변형<br>
z.real(실수부), z.imag(허수부), z.conjugate()(켤레 복소수)를 구할 수 <br>
복소수를 사용하려면 cmath모듈 임포트 

<h3>fraction모듈</h3>
파이썬에서 분수를 다루는 모듈

In [1]:
#assert 문은 뒤의 조건이 True가 아니면 assertion오류를 발생

from fractions import Fraction

def rounding_floats(number1, places):
    return round(number1, places)

def float_to_fractions(number):
    #Fraction(분자, 분모)인 객체 생성
    # *은 iterable한 객체 언패키징
    #객체.from_float(float): 실수를 받아서 fraction객체 생성
    return Fraction(*number.as_integer_ratio())

def get_denominator(number1, number2):
    #a.denominator: 분모 반환
    a= Fraction(number1, number2)
    return a.denominator

def get_numerator(number1, number2):
    #a.numerator: 분자 반환
    a= Fraction(number1, number2)
    return a.numerator

def test_testing_floats():
    number1= 1.25
    number2= 1
    number3= -1
    number4= 5/4
    number6= 6
    assert(rounding_floats(number1, number2)==1.2)
    assert(rounding_floats(number1*10, number3)==10)
    assert(float_to_fractions(number1)== number4)
    assert(get_denominator(number2, number6)== number6)
    assert(get_numerator(number2, number6) == number2)
    print('테스트 통과')
    

#__name__은 해당 파이썬 파일의 이름(그 모듈의 이름)
#해당 파일 안에서 함수를 실행시키면 __name__==__main__
#해당 파일 밖에서 모듈을 임포트해서 실행시키면 __name__은 해당 모듈의 이름이 대입
#다른 파일에서 이 모듈을 임포트 했을때 그 모듈안의 모든 코드가 실행되는 것 

if __name__=='__main__':
    test_testing_floats()

테스트 통과


<h3>decimal 모듈</h3>
정확한 10진법의 부동소수점 숫자가 필요한 경우, 부동소수점 불변 타입인 decimal.Decimal을 사용할 수 있음<br>
Decimal() 메서드는 정수 또는 문자열을 인수로 취함<br>


In [5]:
#generator
sum (0.1 for i in range(10))==1.0
#0.1을 이진수로 정확하게 나타낼 수 없음

from decimal import Decimal
sum(Decimal('0.1') for i in range(10))==Decimal('1.0')


True

<h3>2진수, 8진수, 16진수</h3>

In [9]:
#bin(i)메서드는 정수 i의 2진수 문자열을 반환
print(bin(999))

#oct(i)메서드는 8진수 문자열 반환
print(oct(999))

#hex(i)메서드는 정수 i의 16진수 문자열 반환
print(hex(999))

0b1111100111
0o1747
0x3e7


<h3>연습 문제</h3>

In [37]:
#진법 변환

#10진수인 숫자를 다른 진법의 숫자로 변환, 2<=base<=10
def convert_from_decimal(number, base):
    mul, result= 10, 0
    rep=0
    while number>=base:
        remain= number%base
        result+= remain*mul**rep
        number= number//base
        rep+=1
    result+= number*mul**rep
    return result

def test_convert_from_decimal():
    number, base= 9, 2
    assert(convert_from_decimal(number, base)==1001)
    print('테스트 통과')

if __name__=='__main__':
    test_convert_from_decimal()

#다른진법의 숫자를 10진수로 변환, 2<=base<=10
def convert_to_decimal(number, base):
    rep= 0
    remain, result= 0, 0
    while number>=10:
        remain= number%10
        result+= remain*base**rep
        number//=10
        rep+=1
    result+=number*base**rep
    return result

def test_convert_to_decimal():
    number, base= 9, 2
    assert(convert_from_decimal(number, base)==1001)
    print('테스트 통과!')
    
if __name__=='__main__':
    test_convert_from_decimal()

#10진수를 20이하의 진법으로 변환
def convert_from_decimal_larger_bases(number, base):
    strings='0123456789ABCDEFGHIJ'
    rep, remain=0, 0
    result=''
    while number>=base:
        remain= number%base
        result= strings[remain]+result
        number//=base
    result= strings[number]+result
    return result

def test_convert_from_decimal_larger_bases():
    number, base= 31, 16
    assert(convert_from_decimal_larger_bases(number, base)=='1F')
    print('테스트 통과')

if __name__=='__main__':
    test_convert_from_decimal_larger_bases()
    
#재귀 함수를 사용한 진법 변환
def convert_dec_to_any_base_rec(number, base):
    convertString='0123456789ABCDEF'
    if number<base:
        return convertString[number]
    else:
        return convert_dec_to_any_base_rec(number//base, base)+convertString[number%base]

def test_convert_dec_to_any_base_rec():
    number= 9
    base= 2
    assert(convert_dec_to_any_base_rec(number, base)=='1001')
    print('테스트 통과')
if __name__=='__main__':
    test_convert_dec_to_any_base_rec()

테스트 통과
테스트 통과
테스트 통과
테스트 통과


In [41]:
#최대공약수

def finding_gcd(a, b):
    while(b!=0):
        result=b
        a, b= b, a%b
    return result

def test_finding_gcd():
    number1= 21
    number2= 12
    assert(finding_gcd(number1, number2)==3)
    print('테스트 통과')
    
if __name__=='__main__':
    test_finding_gcd()

테스트 통과


In [43]:
#random 모듈
import random
def testing_random():
    '''random모듈 테스트'''
    values=[1, 2, 3, 4]
    print(random.choice(values))
    print(random.choice(values))
    print(random.choice(values))
    print(random.sample(values, 2))
    print(random.sample(values, 3))
    
    '''values 리스트를 섞는다'''
    random.shuffle(values)
    print(values)
    
    '''0~10의 임의의 정수를 생성'''
    print(random.randint(0, 10))
    print(random.randint(0, 10))

if __name__=='__main__':
    testing_random()

4
1
1
[4, 3]
[1, 2, 3]
[4, 2, 1, 3]
3
6


In [7]:
#피보나치 수열
#피보나치 수열은 첫째 및 둘째 항이 1이며, 그 이후 모든 항은 바로 앞 두항의 합인 수열
import math
def find_fibonacci_seq_iter(n):
    if n<2: return n
    a, b= 0, 1
    for i in range(n):
        a, b= b, a+b
    return a

def find_fibonacci_seq_rec(n):
    if n<2: return n
    return find_fibonacci_seq_rec(n-1)+find_fibonacci_seq_rec(n-2)

def find_fibonacci_seq_form(n):
    sq5= math.sqrt(5)
    phi= (1+ sq5)/2
    #floor: 내림함수
    return int(math.floor(phi**n/sq5))

def test_find_fib():
    #70번째 이상의 결과는 부정확할 수 있음
    n= 10
    assert(find_fibonacci_seq_rec(n)==55)
    assert(find_fibonacci_seq_iter(n)==55)
    assert(find_fibonacci_seq_form(n)==55)
    print('테스트 통과')
    
if __name__=='__main__':
    test_find_fib()

#제너레이터를 이용한 피보나치 수열
def fib_generator():
    a, b=0, 1
    while True:
        yield b
        a, b= b, a+b
        
if __name__=='__main__':
    fg= fib_generator()
    for _ in range(10):
        #개행문자를 빼고 띄어쓰기로 넣음
        print(next(fg), end=' ')

테스트 통과
1 1 2 3 5 8 13 21 34 55 

In [32]:
#소수
#약수로 1과 자기 자신만을 가지는 수
#무차별 대입방법

#제곱근 이용방법
#m * m= n이라고 하면, n이 소수가 아니면 a * b이므로 
#m * m= a* b, m은 실수이고, n, a, b는 자연수
#1)a>m 이면 b<m 2)a=m이면, b=m 3)a<m이면 b>m
#세가지 모두 min(a, b)<=m이므로 m까지의 수까지만 검색하면됨
import math
import random
             
def finding_prime1(number):
    num= abs(number)
    if num<4: return True
    for x in range(2, num):
        if num%x==0:
            return False
    return True

def finding_prime_sqrt(number):
    num= abs(number)
    if num<4 : return True
    for x in range(2, int(math.sqrt(num)+1)):
        if num%x==0:
            return False
    return True

#pow(x, y): x의 y승, pow(x, y, z): x의 y승을 z로 나눈 나머지
def finding_prime_fermat(number):
    if number<= 102:
        for a in range(2, number):
            if pow(a, number-1,number)!=1:
                return False
        return True
    else:
        for i in range(100):
            a= random.randint(2, number-1)
            if pow(a, number -1, number)!=1:
                return False
        return True
def test_finding_prime():
    number1= 17
    number2= 20
    assert(finding_prime1(number1) is True)
    assert(finding_prime1(number2) is False)
    assert(finding_prime_sqrt(number1) is True)
    assert(finding_prime_sqrt(number2) is False)
    assert(finding_prime_fermat(number1) is True)
    assert(finding_prime_fermat(number2) is False)
    print('테스트통과')
    
if __name__=='__main__':
    test_finding_prime()

테스트통과


In [ ]:
#random모듈을 사용하여 n비트 소수 생성
import math
import random
import sys

def finding_prime_sqrt(number):
    num= abs(number)
    if num<4:
        return True
    for x in range(2, int(math.sqrt(num)+1)):
        if number%x==0:
            return False
    return True
#random.randint(a, b): a, b를 포함한 a, b사이의 랜덤한 정수 반환
def generate_prime(number=3):
    while 1:
        p= random.randint(pow(2, number-2), pow(2, number-1)-1)
        p= 2* p +1
        if finding_prime_sqrt(p):
            return p
if __name__=='__main__':
    if len(sys.argv)<2:
        print('usage:generate_prime.py number')
        sys.exit()
    else:
        number= int(sys.argv[1])
        print(generate_prime(number))

<h3>넘파이 패키지</h3>


In [50]:
#넘파이는 파이썬 프로그래밍 언어의 확장 패키지이며, 대규모의 다차원 배열 및 행렬 지원
#넘파이 배열은 임의의 차원을 가짐, 넘파이 모듈의 array메서드를 사용하여
#시퀀스의 시퀀스를 2차원 넘파이 배열로 생성할 수 있음
import numpy as np
np.array(((11, 12, 13), (21, 22, 23), (31, 32, 33)))

#ndim 속성은 배열의 차원수를 알려줌
x= np.array(((11, 12, 13), (21, 22, 23)))
print(x.ndim,'\n')

def testing_numpy():
    '''tests many features of numpy'''
    ax= np.array([1, 2, 3])
    ay= np.array([3, 4, 5])
    print(ax)
    print(ax*2)
    print(ax+10)
    print(np.sqrt(ax))
    print(np.cos(ax))
    print(ax-ay)
    print(np.where(ax<2, ax, 10))
    
    m= np.matrix([ax, ay, ax])
    print(m)
    print(m.T)
    
    grid1= np.zeros(shape=(10, 10), dtype=float)
    grid2= np.ones(shape=(10, 10), dtype=float)
    print(grid1)
    print(grid2)
    print(grid1[1]+10) #열과 행중에 한개만 표시할 경우 행을 표시
    print(grid2[:, 2]*2)
    
if __name__=='__main__':
    testing_numpy()
    
#넘파이 배열은 파이썬 리스트보다 훨씬 효율적


2 

[1 2 3]
[2 4 6]
[11 12 13]
[1.         1.41421356 1.73205081]
[ 0.54030231 -0.41614684 -0.9899925 ]
[-2 -2 -2]
[ 1 10 10]
[[1 2 3]
 [3 4 5]
 [1 2 3]]
[[1 3 1]
 [2 4 2]
 [3 5 3]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


In [51]:
import numpy
import time

#time.time()은 unix timestamp를 소수로 리턴, 정수부는 초, 소수부는 마이크로 초
def trad_version():
    t1= time.time()
    x=range(10000000)
    y=range(10000000)
    z=[]
    for i in range(len(x)):
        z.append(x[i]+y[i])
    return time.time()-t1

def numpy_version():
    t1= time.time()
    x= numpy.arange(1000000)
    y= numpy.arange(1000000)
    z= x+y
    return time.time() - t1

if __name__=='__main__':
    print(trad_version())
    print(numpy_version())

9.080565452575684
0.013362884521484375
